
import java.awt.Toolkit;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class staff5_users extends javax.swing.JFrame {
    
             Connection c;
             String gts="d",value="",value2;
    public staff5_users() {
        initComponents();
        setLocationRelativeTo(null);
         try {
            c=DriverManager.getConnection("jdbc:mysql://localhost:3306/blood_bank", "root", "root");
        } catch (Exception e) 
        {
            JOptionPane.showMessageDialog(this, "error");
        }
         fill_donor();
        icon();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        b_logout = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        t_table = new javax.swing.JTable();
        b_fill_don = new javax.swing.JButton();
        b_fill_rec = new javax.swing.JButton();
        b_delete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Blood Bank");
        setResizable(false);

        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b_logout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/if_exit_3226.png"))); // NOI18N
        b_logout.setText("  log out");
        b_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_logoutActionPerformed(evt);
            }
        });
        jPanel1.add(b_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 110, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, 90, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("users");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 90, 40));

        t_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        t_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(t_table);
        if (t_table.getColumnModel().getColumnCount() > 0) {
            t_table.getColumnModel().getColumn(1).setMinWidth(5);
            t_table.getColumnModel().getColumn(1).setPreferredWidth(5);
            t_table.getColumnModel().getColumn(1).setMaxWidth(5);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 710, 280));

        b_fill_don.setText("Donors");
        b_fill_don.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_fill_donActionPerformed(evt);
            }
        });
        jPanel1.add(b_fill_don, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 90, 30));

        b_fill_rec.setText("recipients ");
        b_fill_rec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_fill_recActionPerformed(evt);
            }
        });
        jPanel1.add(b_fill_rec, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 90, 30));

        b_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/if_Close_53010.png"))); // NOI18N
        b_delete.setText("delete");
        b_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(b_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 90, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/11.jpg"))); // NOI18N
        jLabel1.setText("Donors");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       staff2_main a=new staff2_main();
       a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed
  void icon(){
    setIconImage(Toolkit .getDefaultToolkit().getImage(getClass().getResource("iccon.png")));
}
    void fill_donor()
   { DefaultTableModel dt;
       dt=new DefaultTableModel();
        dt.addColumn("first name");
        dt.addColumn("last name");
        dt.addColumn("blood group");
        dt.addColumn("number");
        dt.addColumn("email");
        dt.addColumn("adress"); 
        dt.addColumn("age");
        dt.addColumn("gender");
        try {
           PreparedStatement st=c.prepareStatement("select donor.donor_id,donor.donor_first_name,donor.donor_last_name,donor.donor_blood_type,donor.donor_number,donor.donor_email,donor.donor_address,donor.donor_age,donor.donor_gender from donor");
     
            ResultSet rs=st.executeQuery();
            while(rs.next())
            {
               
                dt.addRow( new Object[] {rs.getString(2), rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9)});
            } 
            t_table.setModel(dt);
        } catch (SQLException ex) {
            Logger.getLogger(staff5_users.class.getName()).log(Level.SEVERE, null, ex);
        }
    
   }
    private void b_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_logoutActionPerformed
        f1_main a=new f1_main();
      a.setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_b_logoutActionPerformed

    void fillreci(){
         DefaultTableModel dt;
          dt=new DefaultTableModel();
        dt.addColumn("first name");
        dt.addColumn("llast name");
        dt.addColumn("phone");
        dt.addColumn("blood group");
        dt.addColumn("bags");
          try {
           PreparedStatement st=c.prepareStatement("select recieptence.recieptence_first_name,recieptence.recieptence_last_name,recieptence.recieptence_number,recieptence.blood_type2,recieptence.blood_bags from recieptence;");
     
            ResultSet rs=st.executeQuery();
            while(rs.next())
            {
                dt.addRow( new Object[] {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)});
           //     dt.addRow(new Object[]{" "  ,"kk"});
            } 
            t_table.setModel(dt);
        } catch (SQLException ex)
        {
            Logger.getLogger(staff5_users.class.getName()).log(Level.SEVERE, null, ex);
     }}
    private void b_fill_recActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_fill_recActionPerformed
     fillreci();
     gts="r";
    }//GEN-LAST:event_b_fill_recActionPerformed

    private void b_fill_donActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_fill_donActionPerformed
     fill_donor();
     gts="d";
    }//GEN-LAST:event_b_fill_donActionPerformed
 public  boolean isEmpty( ) {
        if (t_table != null && t_table.getModel() != null) {
            return t_table.getModel().getRowCount()<=0?true:false;
        }
        return false;
    }
    void delete(){
        int row = 0 ;
      if(!isEmpty()){          //check table if empty
             row =t_table.getSelectedRow();
             if(row>=0)
                {                        // check if ther is row selected
      
                      try {
                             if(gts.equals("d"))
                             {
                               PreparedStatement st=c.prepareStatement("delete from donor where donor_first_name=? and donor_email=? "  );
                               st.setString(1, value);
                               st.setString(2, value2);
                               st.execute();
                               fill_donor();
                             }
                            if(gts.equals("r"))
                            {
                               PreparedStatement st=c.prepareStatement("delete from recieptence where recieptence_first_name=? and blood_bags=? "  );
                               st.setString(1, value);
                               st.setString(2, value2);
                               st.execute();
                               fillreci();
                           }
                         }
                      
                      catch (SQLException ex) {
                        Logger.getLogger(staff6_staff.class.getName()).log(Level.SEVERE, null, ex);
                      }
               }
                      else
                     JOptionPane.showMessageDialog(this, "no users selected \n select to to delete ");
             
      }
      else
      {
          JOptionPane.showMessageDialog(this, "ther is no staff to delete ", value, HEIGHT);
      }
      // fillTable();
   }
    private void b_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_deleteActionPerformed
       delete();
    }//GEN-LAST:event_b_deleteActionPerformed

    private void t_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_tableMouseClicked
      int row =t_table.getSelectedRow();
       value=t_table.getModel().getValueAt(row, 0).toString();
        value2=t_table.getModel().getValueAt(row, 4).toString();
     //JOptionPane.showConfirmDialog(this, value+""+value2);
    }//GEN-LAST:event_t_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(staff5_users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(staff5_users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(staff5_users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(staff5_users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new staff5_users().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_delete;
    private javax.swing.JButton b_fill_don;
    private javax.swing.JButton b_fill_rec;
    private javax.swing.JButton b_logout;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable t_table;
    // End of variables declaration//GEN-END:variables
}
